### PR TITLE
Add support for reading secrets from files

### PR DESCRIPTION
**Pull request by AlexGustafsson**
See #199.

### CODE REVIEW

**Comment by AlexGustafsson** [comment]
I don't usually develop PHP, so this is likely very rough. I just thought I'd get the work started. I haven't been able to test every aspect of the project with the change, but it works for the database passwords and "should work for the others" as well.

**Comment by Kovah** [comment]
Hi! Thanks for the work you did, appreciate the interest in the project. I probably won't merge the pull request, as it's very rough, like you said. There is probably a better way to achieve this.

**Comment by Kovah** [comment]
Closing this now, the corresponding issue will be kept open.

**Comment by mmozzano** [comment]
Hi,

Any further progress around implementing reading of secrets from a file?  Is this something which is planned?

**Pull request closed without merging**
